feat: 🎸 add create react app and remove biotope from docu
CaritasDeutschland/documentation pull request #27
Opened 2020-11-16 16:20 UTC by iam-robin

## Proposed Changes

  - add documentation about Create React App 
  - remove most of Biotope the descriptions and mark it as deprecated
  - add typescript to 'tools and technologies'

2020-11-18 07:27 UTC, koepferd requested changes

2020-11-18 07:27 UTC, koepferd commented on docs/frontend/build.md
> +In versions `> 2.0.0` the frontend project was based on the Biotope Boilerplate, which was replaced in the course of `version 2.0.0` with the Create React App toolchain.
*< 2.0.0

2020-11-19 09:03 UTC, koepferd approved these changes

2020-11-19 09:59 UTC, iam-robin commented
Merge this PR as soon as `Create React App` Frontend-Version is released

2020-12-15 13:36 UTC, merged